"""Script to generate the javascript required to put all the pieces together.
"""
from pathlib import Path
import json

START = Path(__file__).parent.joinpath("start.py").read_text()
JOY = Path(__file__).parent.joinpath("joy.py").read_text()

LIVECODE_BASE_URL = "https://livecode.fossunited.org"
#LIVECODE_BASE_URL = "http://localhost:8010"

LIVECODE_OPTIONS = {
    "base_url": LIVECODE_BASE_URL,
    "runtime": "python",
    "files": [
        {"filename": "start.py", "contents": START},
        {"filename": "joy.py", "contents": JOY},
    ],
    "command": ["python", "start.py"]
}

def write_file(root, filename, contents):
    p = root.joinpath(filename)
    print("writing", p)
    p.write_text(contents)

def build_js(root):
    jscode = (""
        + "// WARNING: DO NOT EDIT THIS FILE\n"
        + "//\n"
        + "// This file is autogenerated by running:\n"
        + "//    python src/build.py\n"
        + "//\n"
        + "var LIVECODE_OPTIONS = {};".format(json.dumps(LIVECODE_OPTIONS))
    )
    write_file(root, "livecode-options.js", jscode)

def main():
    root = Path(__file__).parent
    root.mkdir(exist_ok=True)
    build_js(root)

if __name__ == "__main__":
    main()